apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: jwt-auth-policy
  namespace: agentgateway-system
spec:
  targetRefs:
  # 仅绑定到业务路由（Keycloak 免认证路由不受影响）
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: admin-api-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: tenant-api-route
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: "http://www.example.com/realms/master"
        jwks:
          remote:
            jwksPath: "/realms/master/protocol/openid-connect/certs"
            cacheDuration: "5m"
            backendRef:
              group: ""
              kind: Service
              name: keycloak
              namespace: keycloak
              port: 8080
      - issuer: "http://www.example.com/realms/acme"
        jwks:
          remote:
            jwksPath: "/realms/acme/protocol/openid-connect/certs"
            cacheDuration: "5m"
            backendRef:
              group: ""
              kind: Service
              name: keycloak
              namespace: keycloak
              port: 8080
      - issuer: "http://www.example.com/realms/globex"
        jwks:
          remote:
            jwksPath: "/realms/globex/protocol/openid-connect/certs"
            cacheDuration: "5m"
            backendRef:
              group: ""
              kind: Service
              name: keycloak
              namespace: keycloak
              port: 8080

